# Generated by Django 4.2.30 on 2026-08-14 15:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viva", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VivaIntegrityEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_hidden", "Tab hidden"),
                            ("tab_returned", "Tab returned"),
                            ("grace_expired", "Grace expired"),
                            ("camera_denied", "Camera denied"),
                            ("frame_uploaded", "Frame uploaded"),
                            ("fullscreen_left", "Fullscreen left"),
                        ],
                        max_length=32,
                    ),
                ),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_events",
                        to="viva.vivasession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VivaProctorFrame",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("storage_key", models.CharField(max_length=1024)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("content_type", models.CharField(default="image/jpeg", max_length=64)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_frames",
                        to="viva.vivasession",
                    ),
                ),
            ],
            options={
                "ordering": ["captured_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vivaintegrityevent",
            index=models.Index(fields=["session", "event_type"], name="viva_vivain_session_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="vivaproctorframe",
            index=models.Index(fields=["session", "captured_at"], name="viva_vivapr_session_cap_idx"),
        ),
    ]
