# Generated by Django 4.2.30 on 2026-08-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0002_integrity_proctor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vivaintegrityevent',
            new_name='viva_vivain_session_d871ad_idx',
            old_name='viva_vivain_session_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='vivaproctorframe',
            new_name='viva_vivapr_session_4472ff_idx',
            old_name='viva_vivapr_session_cap_idx',
        ),
    ]
