# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submissionchunk_end_offset_and_more'),
        ('viva', '0004_vivaslotbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerevaluation',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='confidence',
            field=models.CharField(blank=True, choices=[('high', 'High confidence'), ('medium', 'Medium confidence'), ('low', 'Low confidence'), ('insufficient_evidence', 'Insufficient evidence')], max_length=32),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='evidence_quality',
            field=models.CharField(blank=True, choices=[('direct', 'Direct submission evidence'), ('derived', 'Derived/inferred'), ('stated', 'Student-stated'), ('external', 'External/general knowledge')], max_length=32),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerevaluation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='model_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='retrieval_query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='source_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submissionchunk'),
        ),
        migrations.AlterField(
            model_name='answerevaluation',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='viva.studentanswer'),
        ),
        migrations.AddConstraint(
            model_name='answerevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_deleted', False)), fields=('answer',), name='uniq_current_eval_per_answer'),
        ),
    ]
