"""Central constants for AuditLog.action values."""

SUBMISSION_CREATED = "submission.created"
SUBMISSION_PROCESSED = "submission.processed"
SUBMISSION_EVIDENCE_CREATED = "submission.evidence.created"
QUESTION_GENERATED = "question.generated"
QUESTION_ASKED = "question.asked"
ANSWER_RECEIVED = "answer.received"
EVALUATION_GENERATED = "evaluation.generated"
EVIDENCE_FLAG_CREATED = "evidence.flag.created"
EVIDENCE_FLAG_RESOLVED = "evidence.flag.resolved"
ASSESSMENT_QUESTION_REVIEW = "assessment.question_review"
ASSESSMENT_MODIFY = "assessment.modify"
ASSESSMENT_FINALIZE = "assessment.finalize"
VIVA_CREATE = "viva.create"
VIVA_FINISH = "viva.finish"
