# Generated by Django 4.2.30 on 2026-08-09 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viva', '0001_initial'),
        ('rubrics', '0001_initial'),
        ('submissions', '0001_initial'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentevidence',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viva.studentanswer'),
        ),
        migrations.AddField(
            model_name='assessmentevidence',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='assessments.assessmentcriterion'),
        ),
        migrations.AddField(
            model_name='assessmentcriterion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentcriterion',
            name='rubric_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubrics.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='viva_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='viva.vivasession'),
        ),
    ]
