# Generated by Django 4.2.30 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='disclaimer',
            field=models.CharField(default='AI assessment of submitted-implementation understanding. Instructor review required.', max_length=255),
        ),
    ]
