# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0005_alter_answerevaluation_options_and_more'),
        ('assessments', '0003_alter_assessment_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodification',
            name='action',
            field=models.CharField(choices=[('agree', 'Agree'), ('modify', 'Modify'), ('override', 'Override'), ('insufficient_evidence', 'Mark insufficient evidence'), ('dismiss_flag', 'Dismiss flag'), ('confirm_flag', 'Confirm flag'), ('note', 'Add note')], default='modify', max_length=32),
        ),
        migrations.AddField(
            model_name='assessmentmodification',
            name='answer_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_modifications', to='viva.answerevaluation'),
        ),
        migrations.AddField(
            model_name='assessmentmodification',
            name='viva_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_modifications', to='viva.vivaquestion'),
        ),
        migrations.AlterField(
            model_name='assessmentmodification',
            name='field_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
