# Generated by Django 4.2.30 on 2026-08-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_github_static_ingestion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codesymbol',
            new_name='submissions_snapsho_9599ee_idx',
            old_name='submissions_snapsho_a11c22_idx',
        ),
        migrations.RenameIndex(
            model_name='codesymbol',
            new_name='submissions_reposit_4b8f73_idx',
            old_name='submissions_reposit_b22d33_idx',
        ),
        migrations.RenameIndex(
            model_name='repositoryfile',
            new_name='submissions_snapsho_e8ceaa_idx',
            old_name='submissions_snapsho_9f2b01_idx',
        ),
        migrations.RenameIndex(
            model_name='repositorysnapshot',
            new_name='submissions_owner_e2ea69_idx',
            old_name='submissions_owner_8c1a11_idx',
        ),
        migrations.RenameIndex(
            model_name='submissionchunk',
            new_name='submissions_submiss_be28dc_idx',
            old_name='submissions_submiss_c33e44_idx',
        ),
    ]
