# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_plagiarism_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionchunk',
            name='end_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionchunk',
            name='inner_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='submissionchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionchunk',
            name='section_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submissionchunk',
            name='slide_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionchunk',
            name='start_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='extractor_version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
