# Generated by Django 5.x

from django.db import migrations, models

from courses.join_codes import allocate_join_code


def backfill_join_codes(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.all():
        if course.join_code:
            continue
        course.join_code = allocate_join_code(model=Course)
        course.save(update_fields=["join_code"])


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="join_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shareable code students use to join this course (Classroom-style).",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_join_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="course",
            name="join_code",
            field=models.CharField(
                db_index=True,
                help_text="Shareable code students use to join this course (Classroom-style).",
                max_length=16,
                unique=True,
            ),
        ),
    ]
