# Generated by Django 5.x

from django.db import migrations, models
from django.utils.html import strip_tags


def merge_description_into_instructions(apps, schema_editor):
    Assignment = apps.get_model("assignments", "Assignment")
    for assignment in Assignment.objects.all():
        desc = (assignment.description or "").strip()
        instr = (assignment.instructions or "").strip()
        if not desc:
            continue
        if not instr:
            assignment.instructions = desc
            assignment.save(update_fields=["instructions"])
        elif desc not in strip_tags(instr):
            assignment.instructions = f"{instr}\n\n{desc}"
            assignment.save(update_fields=["instructions"])


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(merge_description_into_instructions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="assignment",
            name="description",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Student-facing brief. May contain limited HTML (bold, italic, lists).",
            ),
        ),
    ]
