# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0005_alter_answerevaluation_options_and_more'),
        ('submissions', '0006_submissionchunk_end_offset_and_more'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='viva_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='viva.vivaquestion'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='viva_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='viva.vivasession'),
        ),
    ]
