# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viva', '0005_alter_answerevaluation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('inconsistency', 'Inconsistency'), ('insufficient_evidence', 'Insufficient evidence'), ('unsupported_claim', 'Unsupported claim'), ('possible_misunderstanding', 'Possible misunderstanding'), ('requires_review', 'Requires instructor review')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('description', models.TextField()),
                ('supporting_evidence', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_flags', to='viva.studentanswer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('viva_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_flags', to='viva.vivaquestion')),
                ('viva_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_flags', to='viva.vivasession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['viva_session', 'status'], name='evidence_ev_viva_se_4b080f_idx'), models.Index(fields=['flag_type', 'severity'], name='evidence_ev_flag_ty_6e375c_idx')],
            },
        ),
    ]
