# Generated by Django 4.2.30 on 2026-08-09 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('submission_specific', 'Submission-specific'), ('methodology', 'Methodology'), ('implementation', 'Implementation'), ('results', 'Results interpretation'), ('critical_thinking', 'Critical thinking'), ('counterfactual', 'Counterfactual'), ('application', 'Application'), ('defense', 'Defense/justification'), ('limitations', 'Limitations')], max_length=32)),
                ('difficulty', models.CharField(default='medium', max_length=16)),
                ('concept', models.CharField(blank=True, max_length=512)),
                ('purpose', models.TextField(blank=True)),
                ('expected_evidence', models.TextField(blank=True)),
                ('source_artifact', models.CharField(blank=True, max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('wording', models.TextField(blank=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_plans', to='submissions.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
