# Generated by Django 4.2.30 on 2026-08-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viva', '0001_initial'),
        ('rubrics', '0001_initial'),
        ('questions', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionplan',
            name='viva_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_plans', to='viva.vivasession'),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.learningoutcome'),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='questions.plannedquestion'),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionplan'),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='rubric_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubrics.rubriccriterion'),
        ),
    ]
