# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submissionchunk_end_offset_and_more'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedquestion',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='model_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='retrieval_query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plannedquestion',
            name='source_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submissionchunk'),
        ),
    ]
