# Generated by Django 4.2.30 on 2026-08-09 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('results', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_logs', to='submissions.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('problem', 'Problem'), ('objective', 'Objective'), ('methodology', 'Methodology'), ('method', 'Method'), ('algorithm', 'Algorithm'), ('dataset', 'Dataset'), ('preprocessing', 'Preprocessing'), ('implementation', 'Implementation'), ('architecture', 'Architecture'), ('component', 'Component'), ('dependency', 'Dependency'), ('result', 'Result'), ('metric', 'Metric'), ('finding', 'Finding'), ('conclusion', 'Conclusion'), ('limitation', 'Limitation'), ('claim', 'Claim'), ('assumption', 'Assumption'), ('term', 'Term')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rag.knowledgenode')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_nodes', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'node_type'], name='rag_knowled_submiss_f7890c_idx')],
            },
        ),
    ]
