# Generated by Django 4.2.30 on 2026-09-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viva', '0005_alter_answerevaluation_options_and_more'),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievallog',
            name='viva_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='viva.vivaquestion'),
        ),
    ]
